export const cards = [
  {
    id: "major_0",
    name: "The Fool",
    image: "/assets/m00.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_1",
    name: "The Magician",
    image: "/assets/m01.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_2",
    name: "The High Priestess",
    image: "/assets/m02.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_3",
    name: "The Empress",
    image: "/assets/m03.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_4",
    name: "The Emperor",
    image: "/assets/m04.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_5",
    name: "The Hierophant",
    image: "/assets/m05.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_6",
    name: "The Lovers",
    image: "/assets/m06.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_7",
    name: "The Chariot",
    image: "/assets/m07.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_8",
    name: "Strength",
    image: "/assets/m08.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_9",
    name: "The Hermit",
    image: "/assets/m09.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_10",
    name: "Wheel of Fortune",
    image: "/assets/m10.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_11",
    name: "Justice",
    image: "/assets/m11.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_12",
    name: "The Hanged Man",
    image: "/assets/m12.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_13",
    name: "Death",
    image: "/assets/m13.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_14",
    name: "Temperance",
    image: "/assets/m14.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_15",
    name: "The Devil",
    image: "/assets/m15.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_16",
    name: "The Tower",
    image: "/assets/m16.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_17",
    name: "The Star",
    image: "/assets/m17.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_18",
    name: "The Moon",
    image: "/assets/m18.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_19",
    name: "The Sun",
    image: "/assets/m19.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_20",
    name: "Judgement",
    image: "/assets/m20.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "major_21",
    name: "The World",
    image: "/assets/m21.jpg",
    arcana: "major",
    suit: null,
  },
  {
    id: "wands_1",
    name: "Ace of Wands",
    image: "/assets/w01.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_2",
    name: "Two of Wands",
    image: "/assets/w02.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_3",
    name: "Three of Wands",
    image: "/assets/w03.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_4",
    name: "Four of Wands",
    image: "/assets/w04.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_5",
    name: "Five of Wands",
    image: "/assets/w05.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_6",
    name: "Six of Wands",
    image: "/assets/w06.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_7",
    name: "Seven of Wands",
    image: "/assets/w07.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_8",
    name: "Eight of Wands",
    image: "/assets/w08.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_9",
    name: "Nine of Wands",
    image: "/assets/w09.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_10",
    name: "Ten of Wands",
    image: "/assets/w10.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_page",
    name: "Page of Wands",
    image: "/assets/w11.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_knight",
    name: "Knight of Wands",
    image: "/assets/w12.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_queen",
    name: "Queen of Wands",
    image: "/assets/w13.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "wands_king",
    name: "King of Wands",
    image: "/assets/w14.jpg",
    arcana: "minor",
    suit: "wands",
  },
  {
    id: "cups_1",
    name: "Ace of Cups",
    image: "/assets/c01.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_2",
    name: "Two of Cups",
    image: "/assets/c02.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_3",
    name: "Three of Cups",
    image: "/assets/c03.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_4",
    name: "Four of Cups",
    image: "/assets/c04.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_5",
    name: "Five of Cups",
    image: "/assets/c05.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_6",
    name: "Six of Cups",
    image: "/assets/c06.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_7",
    name: "Seven of Cups",
    image: "/assets/c07.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_8",
    name: "Eight of Cups",
    image: "/assets/c08.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_9",
    name: "Nine of Cups",
    image: "/assets/c09.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_10",
    name: "Ten of Cups",
    image: "/assets/c10.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_page",
    name: "Page of Cups",
    image: "/assets/c11.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_knight",
    name: "Knight of Cups",
    image: "/assets/c12.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_queen",
    name: "Queen of Cups",
    image: "/assets/c13.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "cups_king",
    name: "King of Cups",
    image: "/assets/c14.jpg",
    arcana: "minor",
    suit: "cups",
  },
  {
    id: "swords_1",
    name: "Ace of Swords",
    image: "/assets/s01.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_2",
    name: "Two of Swords",
    image: "/assets/s02.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_3",
    name: "Three of Swords",
    image: "/assets/s03.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_4",
    name: "Four of Swords",
    image: "/assets/s04.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_5",
    name: "Five of Swords",
    image: "/assets/s05.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_6",
    name: "Six of Swords",
    image: "/assets/s06.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_7",
    name: "Seven of Swords",
    image: "/assets/s07.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_8",
    name: "Eight of Swords",
    image: "/assets/s08.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_9",
    name: "Nine of Swords",
    image: "/assets/s09.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_10",
    name: "Ten of Swords",
    image: "/assets/s10.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_page",
    name: "Page of Swords",
    image: "/assets/s11.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_knight",
    name: "Knight of Swords",
    image: "/assets/s12.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_queen",
    name: "Queen of Swords",
    image: "/assets/s13.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "swords_king",
    name: "King of Swords",
    image: "/assets/s14.jpg",
    arcana: "minor",
    suit: "swords",
  },
  {
    id: "pentacles_1",
    name: "Ace of Pentacles",
    image: "/assets/p01.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_2",
    name: "Two of Pentacles",
    image: "/assets/p02.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_3",
    name: "Three of Pentacles",
    image: "/assets/p03.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_4",
    name: "Four of Pentacles",
    image: "/assets/p04.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_5",
    name: "Five of Pentacles",
    image: "/assets/p05.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_6",
    name: "Six of Pentacles",
    image: "/assets/p06.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_7",
    name: "Seven of Pentacles",
    image: "/assets/p07.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_8",
    name: "Eight of Pentacles",
    image: "/assets/p08.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_9",
    name: "Nine of Pentacles",
    image: "/assets/p09.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_10",
    name: "Ten of Pentacles",
    image: "/assets/p10.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_page",
    name: "Page of Pentacles",
    image: "/assets/p11.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_knight",
    name: "Knight of Pentacles",
    image: "/assets/p12.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_queen",
    name: "Queen of Pentacles",
    image: "/assets/p13.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
  {
    id: "pentacles_king",
    name: "King of Pentacles",
    image: "/assets/p14.jpg",
    arcana: "minor",
    suit: "pentacles",
  },
];
